plugins: [jekyll-paginate]
# Site settings
title: Homepage
email: apoorvjagtap@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apoorv Jagtap's homepage.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://apoorv98.github.io/" # the base hostname & protocol for your site
twitter_username: apoorv_jagtap
github_username: apoorv98
exclude: [vendor]

# paginate settings
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

# collections
collections:
  projects:
    output: true
    permalink: /:collection/:title
